#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/recipes/advanced_crafter/4.mcfunction
#
# Generated by Minecraft Script for 1.13
######
kill @e[type=minecraft:item,limit=1,sort=nearest,nbt={Item:{id:"minecraft:armor_stand",Count:1b,tag:{EntityTag:{NoGravity:1b,Small:1b,DisabledSlots:4144959, Invulnerable:1b,Tags:["ac_lib_advanced_crafter","ac_lib_advanced_crafter_init"]},CustomModelData:701001,ac_lib:{id:"advanced_crafter"},display:{Lore:['{"translate":"Right-click to place","color":"dark_green","italic":false}'],Name:'{"text":"Advanced Crafting Table","italic":false}'}}}}]
