#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/place/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ minecraft:barrel[facing=up]{CustomName:"{\"text\":\"Advanced Crafting Table\",\"italic\":\"false\"}"}
execute align xyz run summon minecraft:armor_stand ~.5 ~.5 ~.5 {NoGravity:1b,Invulnerable:1b,Fire:100s,Marker:1b,Invisible:1b,NoBasePlate:1b,PersistenceRequired:1b,Tags:["ac_lib_advanced_crafter_display"],Rotation:[-90F,0F],ArmorItems:[{},{},{},{id:"minecraft:armor_stand",Count:1b,tag:{CustomModelData:701001}}]}
tag @s remove ac_lib_advanced_crafter_init
