#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/recipes/test/.mcfunction
#
# Generated by Minecraft Script for 1.13
######
kill @e[type=minecraft:item,limit=1,sort=nearest,nbt={Item:{id:"minecraft:diamond_ore", Count:1b, tag: {display: {Name: '{"text":"The Ore"}'}}}}]
