#######
# Compiled from data/ac_lib/functions/management.mcscript
# to .//data/ac_lib/functions/datapack_list_init.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score datapack_list datapack_list matches 1.. run scoreboard players set ac_lib datapack_list 1