#######
# Compiled from data/ac_lib/functions/load.mcscript
# to .//data/ac_lib/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:mcscript/load

scoreboard objectives add ac_temp dummy
scoreboard objectives add ac_creative_menu dummy