#######
# Compiled from data/ac_lib/functions/uninstall.mcscript
# to .//data/ac_lib/functions/uninstall.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard objectives remove ac_temp