#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/recipes/test.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[tag=!ac_lib_advanced_crafter_crafted] unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:1b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:2b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:3b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:10b}]} if block ~ ~ ~ minecraft:barrel{Items:[{Slot:11b,id:"minecraft:stone"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:12b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:19b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:20b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:21b}]} if block ~ ~ ~ minecraft:barrel{Items:[{Slot:5b,id:"minecraft:diamond"}]} if block ~ ~ ~ minecraft:barrel{Items:[{Slot:14b,id:"minecraft:diamond"}]} if block ~ ~ ~ minecraft:barrel{Items:[{Slot:23b,id:"minecraft:diamond"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot: 7b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot: 16b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot: 25b}]} run function ac_lib:advanced_crafter/recipes/test/1

execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:1b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:2b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:3b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:10b}]} if block ~ ~ ~ minecraft:barrel{Items:[{Slot:11b,id:"minecraft:stone"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:12b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:19b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:20b}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:21b}]} if block ~ ~ ~ minecraft:barrel{Items:[{Slot:5b,id:"minecraft:diamond"}]} if block ~ ~ ~ minecraft:barrel{Items:[{Slot:14b,id:"minecraft:diamond"}]} if block ~ ~ ~ minecraft:barrel{Items:[{Slot:23b,id:"minecraft:diamond"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot: 16b,Count:1b,id:"minecraft:diamond_ore",tag:{display: {Name: '{"text":"The Ore"}'}}}]} run function ac_lib:advanced_crafter/recipes/test/2

execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel if block ~ ~ ~ minecraft:barrel{Items:[{Slot:1b}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel if block ~ ~ ~ minecraft:barrel{Items:[{Slot:2b}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel if block ~ ~ ~ minecraft:barrel{Items:[{Slot:3b}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel if block ~ ~ ~ minecraft:barrel{Items:[{Slot:10b}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:11b,id:"minecraft:stone"}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel if block ~ ~ ~ minecraft:barrel{Items:[{Slot:12b}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel if block ~ ~ ~ minecraft:barrel{Items:[{Slot:19b}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel if block ~ ~ ~ minecraft:barrel{Items:[{Slot:20b}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel if block ~ ~ ~ minecraft:barrel{Items:[{Slot:21b}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:5b,id:"minecraft:diamond"}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:14b,id:"minecraft:diamond"}]} run function ac_lib:advanced_crafter/recipes/test/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test] if block ~ ~ ~ minecraft:barrel unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:23b,id:"minecraft:diamond"}]} run function ac_lib:advanced_crafter/recipes/test/3

execute if entity @s[tag=ac_lib_advanced_crafter_crafted_test,tag=ac_lib_advanced_crafter_destroy] run function ac_lib:advanced_crafter/recipes/test/4

