#######
# Compiled from data/ac_lib/functions/creative_menu.mcscript
# to .//data/ac_lib/functions/creative_menu/give.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s ac_creative_menu matches 11 run give @s minecraft:armor_stand{display:{Name:"{\"text\":\"Advanced Crafter\",\"italic\":false}",Lore:["{\"translate\":\"Right-click to place\",\"color\":\"dark_green\",\"italic\":false}"]},CustomModelData:701001,ac_lib:{id:"advanced_crafter"},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["ac_lib_advanced_crafter","ac_lib_advanced_crafter_init"],DisabledSlots:4144959}}
execute if score @s ac_creative_menu matches 11 run scoreboard players reset @s ac_creative_menu

execute if score @s ac_creative_menu matches 21 run give @s minecraft:armor_stand{display:{Name:"{\"text\":\"Advanced Crafter\",\"italic\":false}",Lore:["{\"translate\":\"Right-click to place\",\"color\":\"dark_green\",\"italic\":false}"]},CustomModelData:701001,ac_lib:{id:"advanced_crafter"},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["ac_lib_advanced_crafter","ac_lib_advanced_crafter_init"],DisabledSlots:4144959}} 16
execute if score @s ac_creative_menu matches 21 run scoreboard players reset @s ac_creative_menu
