#######
# Compiled from data/ac_lib/functions/creative_menu.mcscript
# to .//data/ac_lib/functions/creative_menu/select.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s [{"text":" ► ","color":"green"},{"text":"AClib","hoverEvent":{"action":"show_text","value":"Click to select"},"clickEvent":{"action":"run_command","value":"/function ac_lib:creative_menu/menu"}}]
