#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/fix_slots/clear.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.0 if data block ~ ~ ~ Items[{Slot:1b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.1 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.1 if data block ~ ~ ~ Items[{Slot:2b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.2 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.2 if data block ~ ~ ~ Items[{Slot:3b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.3 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.3 if data block ~ ~ ~ Items[{Slot:10b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.10 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.4 if data block ~ ~ ~ Items[{Slot:11b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.11 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.5 if data block ~ ~ ~ Items[{Slot:12b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.12 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.6 if data block ~ ~ ~ Items[{Slot:19b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.19 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.7 if data block ~ ~ ~ Items[{Slot:20b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.20 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.8 if data block ~ ~ ~ Items[{Slot:21b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.21 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.9 if data block ~ ~ ~ Items[{Slot:5b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.5 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.10 if data block ~ ~ ~ Items[{Slot:14b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.14 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.11 if data block ~ ~ ~ Items[{Slot:23b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.23 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsOut.0 if data block ~ ~ ~ Items[{Slot:7b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.7 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsOut.1 if data block ~ ~ ~ Items[{Slot:16b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.16 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsOut.2 if data block ~ ~ ~ Items[{Slot:25b}].tag.PlaceholderTemp run replaceitem block ~ ~ ~ container.25 air

