#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/fix_slots/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:advanced_crafter/fix_slots/clear
execute unless data block ~ ~ ~ Items[{Slot:0b}].tag.Placeholder if entity @s[tag=!ac_lib_advanced_crafter_trash_can] if block ~ ~ ~ minecraft:barrel{Items:[{Slot:0b}]} run function ac_lib:advanced_crafter/fix_slots/0
execute unless data block ~ ~ ~ Items[{Slot:0b}].tag.Placeholder if entity @s[tag=!ac_lib_advanced_crafter_trash_can] run replaceitem block ~ ~ ~ container.0 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:1b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.0 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:1b}]} run function ac_lib:advanced_crafter/fix_slots/1
execute unless data block ~ ~ ~ Items[{Slot:1b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.0 run replaceitem block ~ ~ ~ container.1 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:2b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.1 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:2b}]} run function ac_lib:advanced_crafter/fix_slots/2
execute unless data block ~ ~ ~ Items[{Slot:2b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.1 run replaceitem block ~ ~ ~ container.2 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:3b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.2 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:3b}]} run function ac_lib:advanced_crafter/fix_slots/3
execute unless data block ~ ~ ~ Items[{Slot:3b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.2 run replaceitem block ~ ~ ~ container.3 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:4b}].tag.Placeholder if block ~ ~ ~ minecraft:barrel{Items:[{Slot:4b}]} run function ac_lib:advanced_crafter/fix_slots/4
execute unless data block ~ ~ ~ Items[{Slot:4b}].tag.Placeholder run replaceitem block ~ ~ ~ container.4 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:5b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.9 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:5b}]} run function ac_lib:advanced_crafter/fix_slots/5
execute unless data block ~ ~ ~ Items[{Slot:5b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.9 run replaceitem block ~ ~ ~ container.5 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:6b}].tag.Placeholder if block ~ ~ ~ minecraft:barrel{Items:[{Slot:6b}]} run function ac_lib:advanced_crafter/fix_slots/6
execute unless data block ~ ~ ~ Items[{Slot:6b}].tag.Placeholder run replaceitem block ~ ~ ~ container.6 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:7b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsOut.0 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:7b}]} run function ac_lib:advanced_crafter/fix_slots/7
execute unless data block ~ ~ ~ Items[{Slot:7b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsOut.0 run replaceitem block ~ ~ ~ container.7 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:8b}].tag.Placeholder if block ~ ~ ~ minecraft:barrel{Items:[{Slot:8b}]} run function ac_lib:advanced_crafter/fix_slots/8
execute unless data block ~ ~ ~ Items[{Slot:8b}].tag.Placeholder run replaceitem block ~ ~ ~ container.8 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:10b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.3 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:10b}]} run function ac_lib:advanced_crafter/fix_slots/10
execute unless data block ~ ~ ~ Items[{Slot:10b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.3 run replaceitem block ~ ~ ~ container.10 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:11b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.4 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:11b}]} run function ac_lib:advanced_crafter/fix_slots/11
execute unless data block ~ ~ ~ Items[{Slot:11b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.4 run replaceitem block ~ ~ ~ container.11 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:12b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.5 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:12b}]} run function ac_lib:advanced_crafter/fix_slots/12
execute unless data block ~ ~ ~ Items[{Slot:12b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.5 run replaceitem block ~ ~ ~ container.12 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:13b}].tag.Placeholder if block ~ ~ ~ minecraft:barrel{Items:[{Slot:13b}]} run function ac_lib:advanced_crafter/fix_slots/13
execute unless data block ~ ~ ~ Items[{Slot:13b}].tag.Placeholder run replaceitem block ~ ~ ~ container.13 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:14b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.10 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:14b}]} run function ac_lib:advanced_crafter/fix_slots/14
execute unless data block ~ ~ ~ Items[{Slot:14b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.10 run replaceitem block ~ ~ ~ container.14 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:15b}].tag.Placeholder if block ~ ~ ~ minecraft:barrel{Items:[{Slot:15b}]} run function ac_lib:advanced_crafter/fix_slots/15
execute unless data block ~ ~ ~ Items[{Slot:15b}].tag.Placeholder run replaceitem block ~ ~ ~ container.15 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:16b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsOut.1 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:16b}]} run function ac_lib:advanced_crafter/fix_slots/16
execute unless data block ~ ~ ~ Items[{Slot:16b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsOut.1 run replaceitem block ~ ~ ~ container.16 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:17b}].tag.Placeholder if block ~ ~ ~ minecraft:barrel{Items:[{Slot:17b}]} run function ac_lib:advanced_crafter/fix_slots/17
execute unless data block ~ ~ ~ Items[{Slot:17b}].tag.Placeholder run replaceitem block ~ ~ ~ container.17 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:18b}].tag.Placeholder if entity @s[tag=!ac_lib_advanced_crafter_sink] if block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function ac_lib:advanced_crafter/fix_slots/18
execute unless data block ~ ~ ~ Items[{Slot:18b}].tag.Placeholder if entity @s[tag=!ac_lib_advanced_crafter_sink] run replaceitem block ~ ~ ~ container.18 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:19b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.6 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:19b}]} run function ac_lib:advanced_crafter/fix_slots/19
execute unless data block ~ ~ ~ Items[{Slot:19b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.6 run replaceitem block ~ ~ ~ container.19 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:20b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.7 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:20b}]} run function ac_lib:advanced_crafter/fix_slots/20
execute unless data block ~ ~ ~ Items[{Slot:20b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.7 run replaceitem block ~ ~ ~ container.20 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:21b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.8 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:21b}]} run function ac_lib:advanced_crafter/fix_slots/21
execute unless data block ~ ~ ~ Items[{Slot:21b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.8 run replaceitem block ~ ~ ~ container.21 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:22b}].tag.Placeholder if block ~ ~ ~ minecraft:barrel{Items:[{Slot:22b}]} run function ac_lib:advanced_crafter/fix_slots/22
execute unless data block ~ ~ ~ Items[{Slot:22b}].tag.Placeholder run replaceitem block ~ ~ ~ container.22 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:23b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.11 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:23b}]} run function ac_lib:advanced_crafter/fix_slots/23
execute unless data block ~ ~ ~ Items[{Slot:23b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsIn.11 run replaceitem block ~ ~ ~ container.23 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:24b}].tag.Placeholder if block ~ ~ ~ minecraft:barrel{Items:[{Slot:24b}]} run function ac_lib:advanced_crafter/fix_slots/24
execute unless data block ~ ~ ~ Items[{Slot:24b}].tag.Placeholder run replaceitem block ~ ~ ~ container.24 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:25b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsOut.2 if block ~ ~ ~ minecraft:barrel{Items:[{Slot:25b}]} run function ac_lib:advanced_crafter/fix_slots/25
execute unless data block ~ ~ ~ Items[{Slot:25b}].tag.Placeholder if data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.blockedSlotsOut.2 run replaceitem block ~ ~ ~ container.25 minecraft:gray_stained_glass_pane{Placeholder: 1, PlaceholderTemp:1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:26b}].tag.Placeholder if block ~ ~ ~ minecraft:barrel{Items:[{Slot:26b}]} run function ac_lib:advanced_crafter/fix_slots/26
execute unless data block ~ ~ ~ Items[{Slot:26b}].tag.Placeholder run replaceitem block ~ ~ ~ container.26 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute if block ~ ~-1 ~ minecraft:hopper{Items:[{Slot:0b,tag:{Placeholder:1}}]} run replaceitem block ~ ~-1 ~ container.0 air

execute if block ~ ~-1 ~ minecraft:hopper{Items:[{Slot:1b,tag:{Placeholder:1}}]} run replaceitem block ~ ~-1 ~ container.1 air

execute if block ~ ~-1 ~ minecraft:hopper{Items:[{Slot:2b,tag:{Placeholder:1}}]} run replaceitem block ~ ~-1 ~ container.2 air

execute if block ~ ~-1 ~ minecraft:hopper{Items:[{Slot:3b,tag:{Placeholder:1}}]} run replaceitem block ~ ~-1 ~ container.3 air

execute if block ~ ~-1 ~ minecraft:hopper{Items:[{Slot:4b,tag:{Placeholder:1}}]} run replaceitem block ~ ~-1 ~ container.4 air

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.craftingMode if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b}]} run function ac_lib:advanced_crafter/fix_slots/crafting_mode
execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.ac_lib.craftingMode run replaceitem block ~ ~ ~ container.9 minecraft:crafting_table{Placeholder: 1, ac_lib: {craftingMode: "default"}, display: {Name: '{"text":"Normal Crafting", "italic": false}'}}

