#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/crafted.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:1b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:1b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:2b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:2b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:3b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:3b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:10b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:10b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:11b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:11b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:12b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:12b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:19b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:19b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:20b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:20b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:21b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:21b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:5b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:5b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:14b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:14b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
execute store result score @s ac_temp run data get block ~ ~ ~ Items[{Slot:23b}].Count
scoreboard players remove @s ac_temp 1
execute store result block ~ ~ ~ Items[{Slot:23b}].Count byte 1 run scoreboard players get @s ac_temp
scoreboard players reset @s ac_temp
